development:
  adapter: postgresql
  database: BookWeb_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: BookWeb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: BookWeb_production
  pool: 5
  timeout: 5000
